//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareMonitor.Client.Controller.TemperatureMonitorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TemperatureMonitorServiceReference.IHardwareMonitorTemperatureWCFContract")]
    public interface IHardwareMonitorTemperatureWCFContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorWCFContract/GetCPUsCount", ReplyAction="http://tempuri.org/IHardwareMonitorWCFContract/GetCPUsCountResponse")]
        int GetCPUsCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorWCFContract/GetCPUsCount", ReplyAction="http://tempuri.org/IHardwareMonitorWCFContract/GetCPUsCountResponse")]
        System.Threading.Tasks.Task<int> GetCPUsCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetAvgCPUsTemperature", ReplyAction="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetAvgCPUsTemperatureRe" +
            "sponse")]
        System.Nullable<float> GetAvgCPUsTemperature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetAvgCPUsTemperature", ReplyAction="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetAvgCPUsTemperatureRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Nullable<float>> GetAvgCPUsTemperatureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetCPUTemperature", ReplyAction="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetCPUTemperatureRespon" +
            "se")]
        System.Nullable<float> GetCPUTemperature(int cpuIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetCPUTemperature", ReplyAction="http://tempuri.org/IHardwareMonitorTemperatureWCFContract/GetCPUTemperatureRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Nullable<float>> GetCPUTemperatureAsync(int cpuIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHardwareMonitorTemperatureWCFContractChannel : HardwareMonitor.Client.Controller.TemperatureMonitorServiceReference.IHardwareMonitorTemperatureWCFContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HardwareMonitorTemperatureWCFContractClient : System.ServiceModel.ClientBase<HardwareMonitor.Client.Controller.TemperatureMonitorServiceReference.IHardwareMonitorTemperatureWCFContract>, HardwareMonitor.Client.Controller.TemperatureMonitorServiceReference.IHardwareMonitorTemperatureWCFContract {
        
        public HardwareMonitorTemperatureWCFContractClient() {
        }
        
        public HardwareMonitorTemperatureWCFContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HardwareMonitorTemperatureWCFContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HardwareMonitorTemperatureWCFContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HardwareMonitorTemperatureWCFContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCPUsCount() {
            return base.Channel.GetCPUsCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCPUsCountAsync() {
            return base.Channel.GetCPUsCountAsync();
        }
        
        public System.Nullable<float> GetAvgCPUsTemperature() {
            return base.Channel.GetAvgCPUsTemperature();
        }
        
        public System.Threading.Tasks.Task<System.Nullable<float>> GetAvgCPUsTemperatureAsync() {
            return base.Channel.GetAvgCPUsTemperatureAsync();
        }
        
        public System.Nullable<float> GetCPUTemperature(int cpuIndex) {
            return base.Channel.GetCPUTemperature(cpuIndex);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<float>> GetCPUTemperatureAsync(int cpuIndex) {
            return base.Channel.GetCPUTemperatureAsync(cpuIndex);
        }
    }
}
